
patternslib:: ## Get the latest version of the patternslib
	@if [ ! -d "static/components/patternslib" ]; then \
		git clone https://github.com/Patternslib/Patterns.git static/components/patternslib; \
	else \
		cd static/components/patternslib && git pull; \
	fi;
